spring:
  jackson:
    default-property-inclusion: non_null
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
  instance:
    preferIpAddress: true
hystrix:
  shareSecurityContext: true
signing:
  key: "{cipher}4f2e7d4a4d9494a3d482c0e42be9a1f048ece04c276df7cc62e6fa00825a3d42"